apiVersion: v1
kind: Secret
metadata:
  name: yellowpad-db-secret
  namespace: yellowpad
type: Opaque
stringData:
  POSTGRES_PASSWORD: yellowpad
  DB_PASSWORD: yellowpad
---
apiVersion: v1
kind: Secret
metadata:
  name: yellowpad-minio-secret
  namespace: yellowpad
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
